-- 코드를 작성해주세요
WITH EMP_SCORES AS (
    SELECT 
        EMP_NO, 
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT 
    E_S.SCORE, 
    E.EMP_NO, 
    E.EMP_NAME, 
    E.POSITION, 
    E.EMAIL
FROM EMP_SCORES E_S
JOIN HR_EMPLOYEES E ON E_S.EMP_NO = E.EMP_NO
WHERE E_S.SCORE = (SELECT MAX(SCORE) FROM EMP_SCORES);